import { readFileSync, writeFileSync } from "fs";
import argsParser from "args-parser";
import { SFBuildingPower } from "../src/lib/satisfactoryDatabaseTypes";

/**
 * Reads how power scales with clock speed, and what somersloops a building takes,
 * out of the game's own docs file.
 *
 * This is separate from DocsJsonProcessor because that one writes the whole database
 * in one go, and blanks the icon table unless it is also handed the FModel output.
 * The extracted images are not in the repo, so regenerating the big file in place
 * would lose the icons. Everything here comes from the docs file alone.
 */

function main() {
	const args = argsParser(process.argv);
	const jsonPath = args["json"];
	const tsSavePath = args["ts-save"];
	if (!jsonPath) {
		throw new Error("Please provide the path to the JSON file using --json=<path>.");
	}
	if (!tsSavePath) {
		throw new Error("Please provide the path to save the TypeScript file using --ts-save=<path>.");
	}

	let content = readFileSync(jsonPath, "utf-16le");
	content = content.slice(content.indexOf("["));
	const jsonData = JSON.parse(content);

	const buildings = new Map<string, SFBuildingPower>();
	for (const classDefs of jsonData) {
		for (const classDef of classDefs["Classes"]) {
			if (!("mPowerConsumptionExponent" in classDef)) {
				continue;
			}
			const className = classDef["ClassName"];
			const canTakeSloops = classDef["mCanChangeProductionBoost"] === "True";
			let sloopSlots = canTakeSloops ? Number(classDef["mProductionShardSlotSize"] ?? 0) : 0;
			// The smelter says it takes no somersloops and then says it can be boosted.
			// In the game it takes one, and its boost per slot is the full 1.0 that every
			// other building's slots add up to, so one is what it means.
			if (canTakeSloops && sloopSlots === 0) {
				sloopSlots = 1;
			}
			buildings.set(className, {
				powerExponent: Number(classDef["mPowerConsumptionExponent"]),
				sloopSlots,
				sloopBoostPerSlot: canTakeSloops ? Number(classDef["mProductionShardBoostMultiplier"] ?? 0) : 0,
				sloopPowerExponent: Number(classDef["mProductionBoostPowerConsumptionExponent"]),
			});
		}
	}

	const sorted = [...buildings.entries()].sort(([a], [b]) => a.localeCompare(b));
	const outputJson = JSON.stringify(Object.fromEntries(sorted), null, "\t");
	let outputTs =
		`// Auto-generated by BuildingPowerProcessor.ts\n` +
		`import type { SFBuildingPower } from "./satisfactoryDatabaseTypes";\n\n` +
		`export const buildingPower: Record<string, SFBuildingPower> = ${outputJson};\n`;
	outputTs = outputTs.replace(/^(\t+)*"(\w+?)":/gm, `$1$2:`);

	writeFileSync(tsSavePath, outputTs, "utf-8");
	console.log(`Saved ${sorted.length} buildings to ${tsSavePath}.`);
}

main();
