// Auto-generated by BuildingPowerProcessor.ts
import type { SFBuildingPower } from "./satisfactoryDatabaseTypes";

export const buildingPower: Record<string, SFBuildingPower> = {
	Build_AlienPowerBuilding_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_AssemblerMk1_C: {
		powerExponent: 1.321929,
		sloopSlots: 2,
		sloopBoostPerSlot: 0.5,
		sloopPowerExponent: 2
	},
	Build_Blender_C: {
		powerExponent: 1.321929,
		sloopSlots: 4,
		sloopBoostPerSlot: 0.25,
		sloopPowerExponent: 2
	},
	Build_CentralStorage_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_ConstructorMk1_C: {
		powerExponent: 1.321929,
		sloopSlots: 1,
		sloopBoostPerSlot: 1,
		sloopPowerExponent: 2
	},
	Build_Converter_C: {
		powerExponent: 1.321929,
		sloopSlots: 2,
		sloopBoostPerSlot: 0.5,
		sloopPowerExponent: 2
	},
	Build_DroneStation_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_Elevator_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_FluidTruckStation_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_FoundryMk1_C: {
		powerExponent: 1.321929,
		sloopSlots: 2,
		sloopBoostPerSlot: 0.5,
		sloopPowerExponent: 2
	},
	Build_FrackingExtractor_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_FrackingSmasher_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_GeneratorBiomass_Automated_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_GeneratorCoal_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_GeneratorFuel_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_GeneratorGeoThermal_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_GeneratorNuclear_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_HadronCollider_C: {
		powerExponent: 1.321929,
		sloopSlots: 4,
		sloopBoostPerSlot: 0.25,
		sloopPowerExponent: 2
	},
	Build_HyperTubeJunction_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_HypertubeTJunction_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_IndustrialTank_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_JumpPad_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_JumpPadAdjustable_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_JumpPadTilted_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_LandingPad_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_ManufacturerMk1_C: {
		powerExponent: 1.321929,
		sloopSlots: 4,
		sloopBoostPerSlot: 0.25,
		sloopPowerExponent: 2
	},
	Build_MinerMk1_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_MinerMk2_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_MinerMk3_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_OilPump_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_OilRefinery_C: {
		powerExponent: 1.321929,
		sloopSlots: 2,
		sloopBoostPerSlot: 0.5,
		sloopPowerExponent: 2
	},
	Build_Packager_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_PipeHyperStart_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_PipelineJunction_Cross_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_PipelineJunction_T_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_PipelinePump_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_PipelinePumpMk2_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_PipeStorageTank_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_Portal_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_PortalSatellite_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_PowerStorageMk1_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_QuantumEncoder_C: {
		powerExponent: 1.321929,
		sloopSlots: 4,
		sloopBoostPerSlot: 0.25,
		sloopPowerExponent: 2
	},
	Build_RadarTower_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_ResourceSink_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_ResourceSinkShop_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_SmelterMk1_C: {
		powerExponent: 1.321929,
		sloopSlots: 1,
		sloopBoostPerSlot: 1,
		sloopPowerExponent: 2
	},
	Build_SpaceElevator_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_StorageContainerMk1_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_StorageContainerMk2_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_StorageHazard_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_StorageMedkit_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_StoragePlayer_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_TradingPost_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_TrainDockingStation_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_TrainDockingStationLiquid_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_TrainPlatformEmpty_02_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_TrainPlatformEmpty_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_TrainStation_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_TreeGiftProducer_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_TruckStation_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_Valve_C: {
		powerExponent: 1.6,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	},
	Build_WaterPump_C: {
		powerExponent: 1.321929,
		sloopSlots: 0,
		sloopBoostPerSlot: 0,
		sloopPowerExponent: 2
	}
};
